<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>$(DefineConstants);TRACE;solid</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);TRACE;solid</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Libraries\CodePage\CodePage.csproj" />
    <ProjectReference Include="..\Libraries\RVIO\RVIO.csproj" />
    <ProjectReference Include="..\Libraries\RVZstdSharp\RVZstdSharp.csproj" />
    <ProjectReference Include="..\Libraries\SortMethods\SortMethods.csproj" />
  </ItemGroup>

</Project>
